server.port=8080
spring.application.name=climalert-service
spring.threads.virtual.enabled=true

weather.api.key=438bd907e3a548afaf7232859260607
weather.api.url=https://api.weatherapi.com/v1/current.json
weather.api.ciudad=Buenos Aires

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=arislonimsqui@gmail.com
spring.mail.password=XXXX XXXX XXXX XXXX

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
